#!/bin/bash
selected=$(echo "$HOME/Dots/.i3/config
$HOME/Dots/.Xdefaults
$HOME/Dots/.i3/polybar/config
$HOME/Dots/.i3/compton/.compton.conf
$HOME/Dots/.i3/rofi/rofi.rasi
$HOME/Dots/.i3/rofi/confs
$HOME/Dots/.config/ranger/rc.conf
$HOME/Dots/.config/ranger/rifle.conf
$HOME/Dots/.zshrc
$HOME/Dots/.bashrc
$HOME/Dots/.tmux.conf
$HOME/Dots/.spacevim
$HOME/Dots/.alias" | rofi -dmenu -p "config: ")
[[ -z $selected ]] && exit
gedit $selected
