#!/bin/bash
selected=$(echo "$HOME/Dots/.Xdefaults
$HOME/Dots/.i3/config
$HOME/Dots/.i3/polybar/config
$HOME/Dots/.i3/compton/.compton.conf
$HOME/Dots/.i3/rofi/rofi.rasi
$HOME/Dots/.i3/rofi/scripts
$HOME/Dots/.i3/rofi/configs
$HOME/Dots/.zshrc
$HOME/Dots/.bashrc" | rofi -dmenu -p "config: ")
[[ -z $selected ]] && exit
gedit $selected
