#!/bin/bash
FOREGROUND=$(xrdb -query | grep 'color6:'| awk 'NR==1{print $NF}')
# BACKGROUND=$(xrdb -query | grep 'color0:'| awk 'NR==1{print $NF}')
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_bar -theme-str "*{accent: ${FOREGROUND:-#FFFFFF}; bckgrd: ${BACKGROUND:-#000000};}")
BROWSER=firefox

srch=search
mark=bookmarks
tube=youtube

another=$(echo "$mark
$srch" | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "search: ")


if [ "$another" == "$srch" ] ; then
	surfraw -browser=$BROWSER $(sr -elvi | awk -F'-' '{print $1}' | sed '/:/d' | awk '{$1=$1};1' | rofi "${ROFI_OPTIONS[@]}" -kb-row-select 'Tab' -kb-row-tab 'Control+space' -dmenu -i -p 'bangs: ')

#elif [ "$another" == "$tube" ] ; then
#	exec ~/.config/rofi/menu/uplay

elif [ "$another" == "$mark" ] ; then
  exec ~/.config/rofi/menu/buku

elif [ -z "$another" ] ; then
	surfraw -browser=$BROWSER $(sr -elvi | awk -F'-' '{print $1}' | sed '/:/d' | awk '{$1=$1};1' | rofi "${ROFI_OPTIONS[@]}" -kb-row-select 'Tab' -kb-row-tab 'Control+space' -dmenu -i -p 'bangs: ')

else
	$BROWSER "https://duckduckgo.com/?q=$another"
  #exec nohup $another > /dev/null 2>&1 &
fi
