#!/bin/bash
FOREGROUND=$(xrdb -query | grep 'color6:'| awk 'NR==1{print $NF}')
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_full -theme-str "*{accent: ${FOREGROUND:-#000000};}")
edit_with="kitty --class=til"

another=$(echo "CONFIGS
SCRIPTS
ALIASES
ROFMENU
PROFILE" | awk '{print $(NF-1)}' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "CONFIGS: ")



browse(){
	selected=$(ls "$1/" | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "$1: ")
	[[ -z $selected ]] && exit
	if [[ -f $1/$selected ]]; then
		$edit_with -e nvim $1/$selected
	elif [[ -d $1/$selected ]]; then
		browse $1/$selected
	else
		touch $1/$selected
		chmod +x $1/$selected
		$edit_with -e nvim $1/$selected
	fi
}



if [ "$another" == "PROFILE" ] ; then
	selected=$(echo "$HOME/dots/.zshrc
$HOME/dots/.bashrc
$HOME/dots/.tmux.conf
$HOME/dots/.gitconfig
$HOME/dots/.startup
$HOME/dots/.profile
$HOME/.variables " | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "shell: ")
[[ -z $selected ]] && exit
	$edit_with -e nvim $selected

elif [ "$another" == "CONFIGS" ] ; then
	browse /home/bresilla/dots/.config;

elif [ "$another" == "SYSTEMS" ] ; then
	bash /home/bresilla/dots/.config/rofi/menu/system;

elif [ "$another" == "SCRIPTS" ] ; then
	browse /home/bresilla/dots/.sbin;

elif [ "$another" == "ALIASES" ] ; then
	browse /home/bresilla/dots/.func;

elif [ "$another" == "ROFMENU" ] ; then
	browse /home/bresilla/dots/.config/rofi/menu;

else
    echo $another
fi
