#!/bin/bash
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_full -m 0 -fullscreen)

another=$(echo "CONFIGS
SCRIPTS
FUNCTIS
SHELL
OMZSH" | awk '{print $(NF-1)}' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "SYSTEM: ")



browse(){
	selected=$(ls "$1/" | rofi "${ROFI_OPTIONS[@]}" -dmenu -p "$1: ")
	[[ -z $selected ]] && exit
	if [[ -f $1/$selected ]]; then
		gedit $1/$selected
	elif [[ -d $1/$selected ]]; then
		browse $1/$selected
	else
		touch $1/$selected
		chmod +x $1/$selected
		gedit $1/$selected
	fi
}



if [ "$another" == "SHELL" ] ; then
	selected=$(echo "$HOME/Dots/.zshrc
$HOME/Dots/.bashrc
$HOME/Dots/.tmux.conf
$HOME/Dots/.spacevim
$HOME/Dots/.alias
$HOME/Dots/.Xmodmap
$HOME/.Xdefaults" | rofi "${ROFI_OPTIONS[@]}" -dmenu -p "shell: ")
	[[ -z $selected ]] && exit
	gedit $selected

elif [ "$another" == "CONFIGS" ] ; then
	browse /home/bresilla/Dots/.config;

elif [ "$another" == "SCRIPTS" ] ; then
	browse /home/bresilla/Dots/.scripts;

elif [ "$another" == "FUNCTIS" ] ; then
	browse /home/bresilla/Dots/.func;

elif [ "$another" == "OMZSH" ] ; then
	browse /home/bresilla/Dots/.zsh;

else
    echo $another
fi
