#!/bin/bash
FOREGROUND=$(xrdb -query | grep 'color6:'| awk 'NR==1{print $NF}')
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_full -font "Monoisome 16" -m 0 -fullscreen 0 -theme-str "*{accent: $FOREGROUND;}")
edit_with=alacritty

another=$(echo "CONFIGS
SCRIPTS
ALIASES
ROFMENU
PROFILE" | awk '{print $(NF-1)}' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "CONFIGS: ")



browse(){
	selected=$(ls "$1/" | rofi "${ROFI_OPTIONS[@]}" -dmenu -p "$1: ")
	[[ -z $selected ]] && exit
	if [[ -f $1/$selected ]]; then
		$edit_with -e nvim $1/$selected
	elif [[ -d $1/$selected ]]; then
		browse $1/$selected
	else
		touch $1/$selected
		chmod +x $1/$selected
		$edit_with -e nvim $1/$selected
	fi
}



if [ "$another" == "PROFILE" ] ; then
	selected=$(echo "$HOME/Dots/.zshrc
$HOME/Dots/.bashrc
$HOME/Dots/.profile
$HOME/Dots/.startup
$HOME/Dots/.tmux.conf
$HOME/Dots/.spacevim
$HOME/Dots/.xinitrc" | rofi "${ROFI_OPTIONS[@]}" -dmenu -p "shell: ")
[[ -z $selected ]] && exit
	$edit_with -e nvim $selected

elif [ "$another" == "CONFIGS" ] ; then
	browse /home/bresilla/Dots/.config;

elif [ "$another" == "SCRIPTS" ] ; then
	browse /home/bresilla/Dots/.sbin;

elif [ "$another" == "ALIASES" ] ; then
	browse /home/bresilla/Dots/.func;

elif [ "$another" == "ROFMENU" ] ; then
	browse /home/bresilla/Dots/.config/rofi/menu;

else
    echo $another
fi
