#!/usr/bin/env bash

FOREGROUND=$(xrdb -query | grep 'color6:'| awk 'NR==1{print $NF}')
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_bar -m 0 -width 1500 -theme-str "*{accent: ${FOREGROUND:-#000000};}")

LINK=$(notes ls -o | awk -F' ' '{print $1 "\t\t\t\t" $2}' | column -t -s $'\t' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p 'note: ' | awk '{print $1}') 

[[ -z $LINK ]] && exit 1
alacritty -e nvim /home/bresilla/.local/share/notes-cli/$LINK
