#!/bin/bash

ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_bar -m 0 -width 1500)

another=$(echo "runapp
sudorun
command
files
clipboard
websearch
youtube
localhost
password
bookmarks" | awk '{print $(NF-1)}' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "search: ")


if [ "$another" == "files" ] ; then
	find /media/bresilla/indrive1 -type f | rofi "${ROFI_OPTIONS[@]}" -threads 0 -dmenu -i -p 'locate:' | xargs -r -0 xdg-open;

elif [ "$another" == "websearch" ] ; then
	surfraw -browser=firefox $(sr -elvi | awk -F'-' '{print $1}' | sed '/:/d' | awk '{$1=$1};1' | rofi "${ROFI_OPTIONS[@]}" -kb-row-select 'Tab' -kb-row-tab 'Control+space' -dmenu -i -p 'websearch: ')

elif [ "$another" == "youtube" ] ; then
	exec ~/.config/rofi/menu/uplay

elif [ "$another" == "command" ] ; then
	exec urxvt -hold -e zsh -c $(rofi -theme $HOME/.config/rofi/rofi_bar -m 0 -width 1500 -fuzzy  -lines 0 -show run)

elif [ "$another" == "bookmarks" ] ; then
	exec ~/.config/rofi/menu/marks $HOME/Sets/.notes/bookmarks.wiki

elif [ "$another" == "localhost" ] ; then
	exec ~/.config/rofi/menu/marks $HOME/Sets/.notes/localhost.wiki

elif [ "$another" == "runapp" ] ; then
	rofi "${ROFI_OPTIONS[@]}" -modi 'run,drun' -show drun -show-icons

elif [ "$another" == "password" ] ; then
  exec ~/.sbin/passfill
elif [ "$another" == "clipboard" ] ; then
	rofi "${ROFI_OPTIONS[@]}" -modi "clipboard:greenclip print" -show clipboard

elif [ "$another" == "sudorun" ] ; then
	SUDO_ASKPASS=/home/bresilla/.sbin/askpass rofi "${ROFI_OPTIONS[@]}" -modi 'run,drun' -show drun -theme-str '*{accent: #F10F09;}' -run-command 'sudo -A {cmd}'

elif [ -z "$another" ] ; then
	echo "variable empty"

else
  exec nohup $another > /dev/null 2>&1 &
fi
