#!/bin/bash

ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_full -m 0 -fullscreen)

another=$(echo "RELOAD
COLOR
LOCK
LOGOUT
REBOOT
POWEROFF" | awk '{print $(NF-1)}' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "SYSTEM: ")

script2bin(){
	cat /home/bresilla/pass | sudo -S cp /home/bresilla/Dots/.scripts/* /usr/local/sbin/
	echo "binay files copied"
}

if [ "$another" == "RELOAD" ] ; then
	xrdb -load ~/.Xdefaults; 
	i3-msg reload; 
	i3-msg restart;
	script2bin

elif [ "$another" == "COLOR" ] ; then
	exec ~/.config/rofi/menu/color;

elif [ "$another" == "LOCK" ] ; then
	exec  ~/.config/i3lock/blurlock;
		
elif [ "$another" == "LOGOUT" ] ; then
	prompt "i3-msg exit" LOGOUT
	
elif [ "$another" == "REBOOT" ] ; then
	prompt "reboot" REBOOT
	
elif [ "$another" == "POWEROFF" ] ; then
	prompt "poweroff" POWEROFF	

else
    echo $another
fi


