#!/bin/bash
FOREGROUND=$(xrdb -query | grep 'color6:'| awk 'NR==1{print $NF}')
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_full -font "Monoisome 16" -m 0 -fullscreen 0 -theme-str "*{accent: $FOREGROUND;}")


another=$(echo "POWER
MOUNT" | awk '{print $(NF-1)}' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "SYSTEM: ")

if [ "$another" == "MOUNT" ] ; then
	exec ~/.config/rofi/menu/mount;

elif [ "$another" == "POWER" ] ; then
	exec ~/.config/rofi/menu/logout;

else
  echo $another
fi
