#!/usr/bin/env bash

FOREGROUND=$(xrdb -query | grep 'color6:'| awk 'NR==1{print $NF}')
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_bar -m 0 -width 1500 -theme-str "*{accent: ${FOREGROUND:-#000000};}")

TASK=$(task | tail -n+4 | head -n-2 | awk '{print $0}' | column -t -s $'\t' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p 'task: ' | awk '{print $1}') 

[[ -z $TASK ]] && exit 1
task done $TASK
