#!/bin/bash

ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_bar -m 0 -width 1500)

search='results?search_query='
playlist='&sp=EgIQA0IECAESAA%253D%253D'
entries=0

input=`rofi "${ROFI_OPTIONS[@]}" -dmenu -p "youtube" | sed 's/ /+/g'`

result=$(curl -s "https://www.youtube.com/$search$input" 2>/dev/null) <<< $result

title=`echo -e $(
while IFS= read -r line
  do
    if [[ $line == *'title="'* && $line == *'href="'* && $line == *'data-sessionlink="'* && $line != *'u003'* && $line != *'title="__title__"'* && $line != *'href="//www.youtube.com/upload"'* ]];
      then
	line=$(echo $line | cut -f5 -d'>' | cut -f1 -d '<' |  sed '/^$/d' | perl -MHTML::Entities -pe 'decode_entities($_);')
	if [[ $line != '' && $line != ' ' ]];
	then
	    entries=$((entries+1))
	    echo -e "$line<RETURN>"
        fi
    fi	
done <<< "$result"
) | sed 's/<RETURN>/\n/g' | sed 's/^[ ]//' | rofi "${ROFI_OPTIONS[@]}" -dmenu -p "results"`

while IFS= read -r line
  do
    if [[ $line == *'title="'* && $line == *'href="'* && $line == *'data-sessionlink="'* && $line != *'u003'* && $line != *'title="__title__"'* && $line != *'href="//www.youtube.com/upload"'* ]];
      then 
        bline=$line
        line=$(echo $line | cut -f5 -d'>' | cut -f1 -d '<' |  sed '/^$/d' | perl -MHTML::Entities -pe 'decode_entities($_);')
        if [[ $line != '' && $line != ' ' ]];
          then
            if [[ "$line" == "$title"  ]]; 
	      then
                link="https://www.youtube.com"
                link+=$(echo $bline | cut -f4 -d'>' | cut -f2 -d'"' | cut -f1 -d '"')
	    fi

        fi
    fi  
done <<< "$result"
echo $link
mpv --ytdl-format='bestvideo[height<=?1080]+bestaudio/best' --input-file /home/bresilla/.config/mpv/control --speed 1.0 "$link"
