#!/bin/sh

sed -i "1s/.*/*accent:    ""#$1/" ~/.Xdefaults
xrdb -load ~/.Xdefaults


accent=$(xrdb -query | awk '/accent/{print $2}')
sed -i --follow-symlinks "/accent:/c\	accent: $accent\;" "$HOME/.i3/rofi/rofi.rasi"
sed -i --follow-symlinks "/accent =/c\	accent = $accent" "$HOME/.i3/polybar/config"


i3-msg restart
