#!/bin/sh

value=$(convert $1 -resize 1x1 txt: | grep -v -E '^#.*' | sed -r 's/^.*([0-9A-F]{6}).*/\1/')

echo "$value"

sed -i "1s/.*/*accent:    ""#$value/" ~/.Xdefaults
xrdb -load ~/.Xdefaults

accent=$(xrdb -query | awk '/accent/{print $2}')
sed -i --follow-symlinks "/accent:/c\	accent: $accent\;" "$HOME/.i3/rofi/rofi.rasi"
sed -i --follow-symlinks "/accent =/c\	accent = $accent" "$HOME/.i3/polybar/config"

i3-msg restart
