#!/bin/sh

value=$(convert $1 -resize 1x1 txt: | grep -v -E '^#.*' | sed -r 's/^.*([0-9A-F]{6}).*/\1/')

echo "$value"

sed -i "1s/.*/*accent:    ""#$value/" ~/.Xdefaults
xrdb -load ~/.Xdefaults
i3-msg restart


### move this file to "/bin/[name]" and make it executable "sudo chmod +x /bin/[name]"
