#!/usr/bin/env bash
# Take password prompt from STDIN, print password to STDOUT

rofi -theme /home/bresilla/.config/rofi/rofi_full -m 0 -fullscreen \
	-dmenu \
	-password \
	-padding 2000 \
	-theme-str '*{accent: #F10F09;}' \
	-font "Monoisome 64" \
	-p "$(printf " -	" | sed s/://)"
