#!/usr/bin/env sh


if [ -f $BIB ]; then
    curl -s http://api.crossref.org/works/$1/transform/application/x-bibtex | bat;
    echo "\nDo you wish to add reference to "$BIB"?\n";
    select yn in "Yes" "No"; do
        case $yn in
            Yes ) echo >> $BIB; curl -s "http://api.crossref.org/works/$1/transform/application/x-bibtex" >> $BIB; echo >> $BIB; echo "\n${GREEN}Reference added!"; echo ""; break;;
            No ) echo "\n${ORANGE}No changes made!"; echo ""; break;;
        esac
    done;
else
    echo "\nYour bibliograpy file ${RED}\$BIB is not defined or found${NOCOLOR}, please define it and try again!\n";
fi;

