#!/usr/bin/env bash
file="/home/$USER/Dots/.config/searcher"

if [ "$1" == "add" ] ; then
    $EDITOR $file
elif [ "$1" == "edit" ] ; then
    $EDITOR $file
elif [ "$1" == "list" ] ; then
    cat $file | grep "\S"
else
    selected=$( cut -d\| -f1 $file | fzy)
    if [ $selected ] ; then
        read -p "Search $selected: " uservar
        cat $file | while read line
        do
            name=$(echo $line | cut -d\| -f1)
            link=$(echo $line | cut -d\| -f2)
            [[ "$selected" == "$name" ]] && $BROWSER $link$uservar
        done
    fi
fi
