#!/usr/bin/env bash

screen_1_width=$(xrandr | grep '*' | awk 'NR==1 {print substr($1,1,4)}')
screen_1_heigh=$(xrandr | grep '*' | awk 'NR==1 {print substr($1,6,4)}')
screen_2_width=$(xrandr | grep '*' | awk 'NR==2 {print substr($1,1,4)}')
screen_2_heigh=$(xrandr | grep '*' | awk 'NR==2 {print substr($1,6,4)}')

window_width=$(expr $screen_1_width / 2)
window_heigh=$(expr $screen_1_heigh / 2)
xoffset=$(expr $screen_1_width / 2 - ${2:-$window_width} / 2)
[[ -z "$screen_2_heigh" ]] && screen_2_heigh=0
yoffset=$(expr $screen_1_heigh / 2 - ${3:-$window_heigh} / 2 + $screen_2_heigh + 30)
#yoffset=$(expr $screen_1_heigh / 2 - ${3:-$window_heigh} / 2)

tmass -l /home/bresilla/.config/tmux load $1
exec tdrop -w ${2:-$window_width} -h ${3:-$window_heigh} -x ${4:-$xoffset} -y ${5:-$yoffset} -n $1 -f "-e tmux attach -t $1" kitty
