#!/usr/bin/env bash

EVENTS="CREATE,CLOSE_WRITE,DELETE,MODIFY,MOVED_FROM,MOVED_TO"

inotifywait -e "$EVENTS" -m -r --format '%:e %f' . | (
  WAITING="";
  while true; do
    LINE="";
    read -t 1 LINE;
      if test -z "$LINE"; then
        if test ! -z "$WAITING"; then
          echo "CHANGE";
          WAITING="";
        fi;
      else
        WAITING=1;
      fi;
  done) | (
  while true; do
    read TMP;
    rsync -a -r -t -v --exclude={.git,.gitignore,README.md} --progress -s $HOME/Dots/ $HOME
  done
)
