#!/usr/bin/env sh

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 1; done

# Launch top and bottom

if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar -c ~/.i3/polybar/config top &
    MONITOR=$m polybar -c ~/.i3/polybar/config bottom &
  done
else
  polybar top & polybar bottom &
fi
