# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Aliases for commands. The keys of the given dictionary are the
# aliases, while the values are the commands they map to.
# Type: Dict
c.aliases = {'Q': 'close', 'q': 'tab-close', 'w': 'session-save', 'wq': 'quit --save'}

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Shrink the completion to be smaller than the configured size if there
# are no scrollbars.
# Type: Bool
c.completion.shrink = True

# Width (in pixels) of the scrollbar in the completion window.
# Type: Int
c.completion.scrollbar.width = 0

# Padding (in pixels) of the scrollbar handle in the completion window.
# Type: Int
c.completion.scrollbar.padding = 0

# Padding (in pixels) for the statusbar.
# Type: Padding
c.statusbar.padding = {'bottom': 2, 'left': 5, 'right': 5, 'top': 2}

# Position of the status bar.
# Type: VerticalPosition
# Valid values:
#   - top
#   - bottom
c.statusbar.position = 'bottom'

# How to behave when the close mouse button is pressed on the tab bar.
# Type: String
# Valid values:
#   - new-tab: Open a new tab.
#   - close-current: Close the current tab.
#   - close-last: Close the last tab.
#   - ignore: Don't do anything.
c.tabs.close_mouse_button_on_bar = 'new-tab'

# Scaling factor for favicons in the tab bar. The tab size is unchanged,
# so big favicons also require extra `tabs.padding`.
# Type: Float
c.tabs.favicons.scale = 1.0

# When to show favicons in the tab bar.
# Type: String
# Valid values:
#   - always: Always show favicons.
#   - never: Always hide favicons.
#   - pinned: Show favicons only on pinned tabs.
c.tabs.favicons.show = 'never'

# Position of new tabs which are not opened from another tab. See
# `tabs.new_position.stacking` for controlling stacking behavior.
# Type: NewTabPosition
# Valid values:
#   - prev: Before the current tab.
#   - next: After the current tab.
#   - first: At the beginning.
#   - last: At the end.
c.tabs.new_position.unrelated = 'last'

# Padding (in pixels) around text for tabs.
# Type: Padding
c.tabs.padding = {'bottom': 2, 'left': 5, 'right': 5, 'top': 2}

# Width (in pixels) of the progress indicator (0 to disable).
# Type: Int
c.tabs.indicator.width = 0

# Padding (in pixels) for tab indicators.
# Type: Padding
c.tabs.indicator.padding = {'bottom': 2, 'left': 2, 'right': 2, 'top': 2}

# Default zoom level.
# Type: Perc
c.zoom.default = '200%'

# Text color of the completion widget. May be a single color to use for
# all columns or a list of three colors, one for each column.
# Type: List of QtColor, or QtColor
c.colors.completion.fg = '#c5c4c4'

# Background color of the completion widget for odd rows.
# Type: QssColor
c.colors.completion.odd.bg = '#181414'

# Background color of the completion widget for even rows.
# Type: QssColor
c.colors.completion.even.bg = '#181414'

# Foreground color of completion widget category headers.
# Type: QtColor
c.colors.completion.category.fg = '#c5c4c4'

# Background color of the completion widget category headers.
# Type: QssColor
c.colors.completion.category.bg = '#181414'

# Top border color of the completion widget category headers.
# Type: QssColor
c.colors.completion.category.border.top = '#181414'

# Bottom border color of the completion widget category headers.
# Type: QssColor
c.colors.completion.category.border.bottom = '#181414'

# Foreground color of the selected completion item.
# Type: QtColor
c.colors.completion.item.selected.fg = '#c5c4c4'

# Background color of the selected completion item.
# Type: QssColor
c.colors.completion.item.selected.bg = '#ff7c5d'

# Top border color of the completion widget category headers.
# Type: QssColor
c.colors.completion.item.selected.border.top = '#181414'

# Bottom border color of the selected completion item.
# Type: QssColor
c.colors.completion.item.selected.border.bottom = '#181414'

# Foreground color of the matched text in the completion.
# Type: QtColor
c.colors.completion.match.fg = '#ffb580'

# Color of the scrollbar handle in the completion view.
# Type: QssColor
c.colors.completion.scrollbar.fg = '#c5c4c4'

# Color of the scrollbar in the completion view.
# Type: QssColor
c.colors.completion.scrollbar.bg = '#181414'

# Background color for the download bar.
# Type: QssColor
c.colors.downloads.bar.bg = '#181414'

# Color gradient stop for download backgrounds.
# Type: QtColor
c.colors.downloads.stop.bg = '#ffb580'

# Color gradient interpolation system for download backgrounds.
# Type: ColorSystem
# Valid values:
#   - rgb: Interpolate in the RGB color system.
#   - hsv: Interpolate in the HSV color system.
#   - hsl: Interpolate in the HSL color system.
#   - none: Don't show a gradient.
c.colors.downloads.system.bg = 'none'

# Foreground color for downloads with errors.
# Type: QtColor
c.colors.downloads.error.fg = '#c5c4c4'

# Background color for downloads with errors.
# Type: QtColor
c.colors.downloads.error.bg = '#ff7c5d'

# Font color for hints.
# Type: QssColor
c.colors.hints.fg = '#181414'

# Background color for hints. Note that you can use a `rgba(...)` value
# for transparency.
# Type: QssColor
c.colors.hints.bg = '#ff3d44'

# Font color for the matched part of hints.
# Type: QssColor
c.colors.hints.match.fg = '#ff6f04'

# Text color for the keyhint widget.
# Type: QssColor
c.colors.keyhint.fg = '#c5c4c4'

# Highlight color for keys to complete the current keychain.
# Type: QssColor
c.colors.keyhint.suffix.fg = '#ff3d44'

# Background color of the keyhint widget.
# Type: QssColor
c.colors.keyhint.bg = '#181414'

# Foreground color of an error message.
# Type: QssColor
c.colors.messages.error.fg = '#c5c4c4'

# Background color of an error message.
# Type: QssColor
c.colors.messages.error.bg = '#ff7c5d'

# Border color of an error message.
# Type: QssColor
c.colors.messages.error.border = '#ff7c5d'

# Foreground color of a warning message.
# Type: QssColor
c.colors.messages.warning.fg = '#c5c4c4'

# Background color of a warning message.
# Type: QssColor
c.colors.messages.warning.bg = '#881100'

# Border color of a warning message.
# Type: QssColor
c.colors.messages.warning.border = '#881100'

# Foreground color of an info message.
# Type: QssColor
c.colors.messages.info.fg = '#c5c4c4'

# Background color of an info message.
# Type: QssColor
c.colors.messages.info.bg = '#ff6f04'

# Border color of an info message.
# Type: QssColor
c.colors.messages.info.border = '#ff6f04'

# Foreground color for prompts.
# Type: QssColor
c.colors.prompts.fg = '#c5c4c4'

# Border used around UI elements in prompts.
# Type: String
c.colors.prompts.border = '1px solid #181414'

# Background color for prompts.
# Type: QssColor
c.colors.prompts.bg = '#181414'

# Background color for the selected item in filename prompts.
# Type: QssColor
c.colors.prompts.selected.bg = '#ff7c5d'

# Foreground color of the statusbar.
# Type: QssColor
c.colors.statusbar.normal.fg = '#c5c4c4'

# Background color of the statusbar.
# Type: QssColor
c.colors.statusbar.normal.bg = '#181414'

# Foreground color of the statusbar in insert mode.
# Type: QssColor
c.colors.statusbar.insert.fg = '#181414'

# Background color of the statusbar in insert mode.
# Type: QssColor
c.colors.statusbar.insert.bg = '#ff6f04'

# Foreground color of the statusbar in passthrough mode.
# Type: QssColor
c.colors.statusbar.passthrough.fg = '#c5c4c4'

# Background color of the statusbar in passthrough mode.
# Type: QssColor
c.colors.statusbar.passthrough.bg = '#ff6f04'

# Foreground color of the statusbar in private browsing mode.
# Type: QssColor
c.colors.statusbar.private.fg = '#c5c4c4'

# Background color of the statusbar in private browsing mode.
# Type: QssColor
c.colors.statusbar.private.bg = '#181414'

# Foreground color of the statusbar in command mode.
# Type: QssColor
c.colors.statusbar.command.fg = '#c5c4c4'

# Background color of the statusbar in command mode.
# Type: QssColor
c.colors.statusbar.command.bg = '#181414'

# Foreground color of the statusbar in private browsing + command mode.
# Type: QssColor
c.colors.statusbar.command.private.fg = '#c5c4c4'

# Background color of the statusbar in private browsing + command mode.
# Type: QssColor
c.colors.statusbar.command.private.bg = '#181414'

# Foreground color of the statusbar in caret mode.
# Type: QssColor
c.colors.statusbar.caret.fg = '#c5c4c4'

# Background color of the statusbar in caret mode.
# Type: QssColor
c.colors.statusbar.caret.bg = '#ffb580'

# Foreground color of the statusbar in caret mode with a selection.
# Type: QssColor
c.colors.statusbar.caret.selection.fg = '#c5c4c4'

# Background color of the statusbar in caret mode with a selection.
# Type: QssColor
c.colors.statusbar.caret.selection.bg = '#ffb580'

# Background color of the progress bar.
# Type: QssColor
c.colors.statusbar.progress.bg = '#c5c4c4'

# Default foreground color of the URL in the statusbar.
# Type: QssColor
c.colors.statusbar.url.fg = '#c5c4c4'

# Foreground color of the URL in the statusbar on error.
# Type: QssColor
c.colors.statusbar.url.error.fg = '#ff7c5d'

# Foreground color of the URL in the statusbar for hovered links.
# Type: QssColor
c.colors.statusbar.url.hover.fg = '#ff6f04'

# Foreground color of the URL in the statusbar on successful load
# (http).
# Type: QssColor
c.colors.statusbar.url.success.http.fg = '#c5c4c4'

# Foreground color of the URL in the statusbar on successful load
# (https).
# Type: QssColor
c.colors.statusbar.url.success.https.fg = '#d32a00'

# Foreground color of the URL in the statusbar when there's a warning.
# Type: QssColor
c.colors.statusbar.url.warn.fg = '#881100'

# Background color of the tab bar.
# Type: QtColor
c.colors.tabs.bar.bg = '#181414'

# Color for the tab indicator on errors.
# Type: QtColor
c.colors.tabs.indicator.error = '#ff7c5d'

# Color gradient interpolation system for the tab indicator.
# Type: ColorSystem
# Valid values:
#   - rgb: Interpolate in the RGB color system.
#   - hsv: Interpolate in the HSV color system.
#   - hsl: Interpolate in the HSL color system.
#   - none: Don't show a gradient.
c.colors.tabs.indicator.system = 'none'

# Foreground color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.fg = '#c5c4c4'

# Background color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.bg = '#181414'

# Foreground color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.fg = '#c5c4c4'

# Background color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.bg = '#181414'

# Foreground color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.fg = '#181414'

# Background color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.bg = '#ff6f04'

# Foreground color of selected even tabs.
# Type: QtColor
c.colors.tabs.selected.even.fg = '#181414'

# Background color of selected even tabs.
# Type: QtColor
c.colors.tabs.selected.even.bg = '#ff6f04'

# Background color for webpages if unset (or empty to use the theme's
# color).
# Type: QtColor
c.colors.webpage.bg = '#181414'

# Default monospace fonts. Whenever "monospace" is used in a font
# setting, it's replaced with the fonts listed here.
# Type: Font
c.fonts.monospace = '\'Iosevka Term SS01\', \'Droid Sans Mono\', Terminus, Monospace, "DejaVu Sans Mono", Monaco, "Bitstream Vera Sans Mono", "Andale Mono", "Courier New", Courier, "Liberation Mono", monospace, Fixed, Consolas, Terminal'

# Font used in the completion widget.
# Type: Font
c.fonts.completion.entry = '12pt monospace'

# Font used in the completion categories.
# Type: Font
c.fonts.completion.category = 'bold 12pt monospace'

# Font used for the debugging console.
# Type: QtFont
c.fonts.debug_console = '12pt monospace'

# Font used for the downloadbar.
# Type: Font
c.fonts.downloads = '12pt monospace'

# Font used for the hints.
# Type: Font
c.fonts.hints = 'bold 12pt monospace'

# Font used in the keyhint widget.
# Type: Font
c.fonts.keyhint = '12pt monospace'

# Font used for error messages.
# Type: Font
c.fonts.messages.error = '12pt monospace'

# Font used for info messages.
# Type: Font
c.fonts.messages.info = '12pt monospace'

# Font used for warning messages.
# Type: Font
c.fonts.messages.warning = '12pt monospace'

# Font used for prompts.
# Type: Font
c.fonts.prompts = '12pt sans-serif'

# Font used in the statusbar.
# Type: Font
c.fonts.statusbar = '12pt monospace'

# Font used in the tab bar.
# Type: QtFont
c.fonts.tabs = '12pt monospace'

config.source('qutewal.py')
