#! /bin/sh

#########################################################################################################################################
#|||	SETTINGS
#########################################################################################################################################
bspc config border_width         0
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   true
bspc config auto_alternate true


#########################################################################################################################################
#|||	WORKSPACES & MONITORS
#########################################################################################################################################
bspc monitor eDP1 -d 001 002 003 004 005
bspc monitor DP1 -d 006 007 008 009 010

#########################################################################################################################################
#|||	ASSIGNMENTS
#########################################################################################################################################

bspc rule -a  kitty state=floating
bspc rule -a  mpv state=floating
bspc rule -a  MPlayer state=floating
bspc rule -a  matplotlib state=floating
bspc rule -a  URxvt state=floating

bspc rule -a  Firefox desktop=^9
bspc rule -a  Code desktop=^2
bspc rule -a  Nautilus desktop=^1

#########################################################################################################################################
#|||	KICKSTART
#########################################################################################################################################
bash ~/.startup -r &
bash ~/.startup &
