#!/bin/bash	
	
clipp=$(xsel --clipboard)
clipp=${clipp:1:6}

if [[ $clipp =~ ^([[:xdigit:]]{3}){1,2}$ ]]; then 
	sed -i "1s/.*/*accent:    ""#$clipp/" ~/.Xdefaults
	xrdb -load ~/.Xdefaults

	sed -i --follow-symlinks "/accent:/c\	accent: #$clipp\;" "$HOME/.i3/rofii/rofi_full"
	sed -i --follow-symlinks "/accent:/c\	accent: #$clipp\;" "$HOME/.i3/rofii/rofi_bar"
	sed -i --follow-symlinks "/accent:/c\	accent: #$clipp\;" "$HOME/.i3/rofii/rofi_menu"
	sed -i --follow-symlinks "/accent =/c\	accent = #$clipp" "$HOME/.i3/polybar/polybar"
	sed -i --follow-symlinks "/keyhlcolor/c\	keyhlcolor = #$clipp\FF" "$HOME/.i3/i3lock/lock"

	sed -i --follow-symlinks "/accent:/c\	accent: #$clipp\;" "$HOME/Dots/.i3/rofii/rofi_full"
	sed -i --follow-symlinks "/accent:/c\	accent: #$clipp\;" "$HOME/Dots/.i3/rofii/rofi_bar"
	sed -i --follow-symlinks "/accent:/c\	accent: #$clipp\;" "$HOME/Dots/.i3/rofii/rofi_menu"
	sed -i --follow-symlinks "/accent =/c\	accent = #$clipp" "$HOME/Dots/.i3/polybar/polybar"
	sed -i --follow-symlinks "/keyhlcolor/c\	keyhlcolor = #$accent\FF" "$HOME/Dots/.i3/i3lock/lock"
	i3-msg restart
else
    echo "invalid color"; 
fi

