#!/bin/bash	
	
clipp=$(xsel --clipboard)
clipp=${clipp:1:6}

sed -i "1s/.*/*accent:    ""#$clipp/" ~/.Xdefaults
xrdb -load ~/.Xdefaults

accent=$(xrdb -query | awk '/accent/{print $2}')
sed -i --follow-symlinks "/accent:/c\	accent: $accent\;" "$HOME/.i3/rofi"
sed -i --follow-symlinks "/accent:/c\	accent: $accent\;" "$HOME/.i3/rofi2"
sed -i --follow-symlinks "/accent =/c\	accent = $accent" "$HOME/.i3/polybar"
sed -i --follow-symlinks "/keyhlcolor/c\	keyhlcolor = $accent\FF" "$HOME/.i3/lock"

sed -i --follow-symlinks "/accent:/c\	accent: $accent\;" "$HOME/Dots/.i3/rofi"
sed -i --follow-symlinks "/accent:/c\	accent: $accent\;" "$HOME/Dots/.i3/rofi2"
sed -i --follow-symlinks "/accent =/c\	accent = $accent" "$HOME/Dots/.i3/polybar"
sed -i --follow-symlinks "/keyhlcolor/c\	keyhlcolor = $accent\FF" "$HOME/Dots/.i3/lock"

i3-msg restart
