#!/usr/bin/env bash


xmodmap -e "remove control = Control_R";
sleep .1
xmodmap -e "add Mod3 = Control_R";
sleep .1
xmodmap -e "clear lock";
sleep .1
xmodmap -e "keycode 66 = Escape";
sleep .1
setxkbmap -option caps:escape;

