include(CPack)
include(GNUInstallDirs)
###### CPACK PACKAGING SYSTEM ######
# Set up packager.
set(CPACK_PROJECT_NAME                  ${PROJECT_NAME})
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY   "${CMAKE_PROJECT_NAME}")
set(CPACK_PACKAGE_VENDOR                "${CMAKE_PROJECT_NAME}_VENDOR_NAME")
set(CPACK_PACKAGE_DESCRIPTION_FILE      "${PROJECT_PATH}/README.md")
set(CPACK_RESOURCE_FILE_LICENSE         "${PROJECT_PATH}/LICENSE.md")
set(CPACK_PACKAGE_VERSION_MAJOR         "${${CMAKE_PROJECT_NAME}_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR         "${${CMAKE_PROJECT_NAME}_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH         "${${CMAKE_PROJECT_NAME}_VERSION_PATCH}")
set(CPACK_PACKAGE_INSTALL_DIRECTORY     "${CMAKE_PROJECT_NAME}")
set(CPACK_MONOLITHIC_INSTALL            1)


