#!/usr/bin/env sh

cpu=$(/home/bresilla/.config/tmux/modules/cpu-stat)
netspeed=$(/home/bresilla/.config/tmux/modules/netwidth)
mem=$(free | grep Mem | awk '{print (100 - ($4/($3+$4) * 100.0));}')
bat=$(acpi | awk '{print $4}' | tr -d '%,')
chrg=$(acpi | awk '{print $3}' | tr -d '%,')
tmu=$(uptime | awk '{print $1}' | cut -d: -f1,2)
upt=$(uptime | awk -F, '{sub(".*up ",x,$1);print $1}')
task=$(task ids)
wat=$(echo - | awk "{printf \"%.1f\", $(($(cat /sys/class/power_supply/BAT0/current_now) * \
  $(cat /sys/class/power_supply/BAT0/voltage_now))) / 1000000000000 }")

cpu=${cpu%.*}
mem=${mem%.*}

foreground="#[fg=colour15]"
blackTX="#[fg=colour0]"
blackBG="#[bg=colour0]"
blueTX="#[fg=colour1]"
blueBG="#[bg=colour1]"
orangeBG="#[bg=colour208]"
orangeTX="#[fg=colour208]"
redBG="#[bg=colour196]"
redTX="#[fg=colour196]"
grayBG="#[bg=colour8]"
grayTX="#[fg=colour8]"
sealTX="#[fg=colour59]"
defaBG="#[bg=default]"
defaTX="#[fg=default]"
BLD="#[bold]"
NLD="#[nobold]"


if [ $(cat /proc/acpi/bbswitch | awk 'NF>1{print $NF}') == ON ]; then
    power="$sealTX $redTX$BLD$wat W $NLD"
else
    power="$sealTX $wat W "
fi

if [ "$chrg" != "Discharging" ] ;then
    encap1="["
    encap2="]"
fi

battery="$grayTX$grayBG $blackTX$encap1$bat%$encap2$grayBG "
memo="$blueTX$blueBG $foreground$mem% "
spacer="$blackTX$blackBG"

if (( cpu > 80 )); then
    proc="$redTX$redBG $BLD$foreground$cpu% "
elif (( cpu > 50 )); then
    proc="$orangeTX$orangeBG $BLD$foreground$cpu% "
else
    proc="$blueTX$blueBG $foreground$cpu% "
fi

RIGHT_STATUS="$power$battery$memo$spacer$proc"

main="$blueBG$foreground $BLD$tmu$NLD $blueTX$grayBG"
name="$blackTX $netspeed $grayTX$defaBG"


if [[ -n "${task/[ ]*\n/}" ]]
then
    utim="$sealTX #S/#W $blackTX$redBG $BLD$blackTX$task$redTX $NLD$blackBG"
else
    utim="$sealTX #S/#W "
fi


LEFT_STATUS="$main$name$utim"

if [ "$1" == "RIGHT" ] ;then
    echo $RIGHT_STATUS
elif [ "$1" == "LEFT" ] ;then
    echo $LEFT_STATUS
fi
