#!/usr/bin/env sh

cpu=$(/home/bresilla/.config/tmux/modules/cpu-stat)
netspeed=$(/home/bresilla/.config/tmux/modules/netwidth)
mem=$(free | grep Mem | awk '{print (100 - ($4/($3+$4) * 100.0));}')
bat=$(acpi | awk '{print $4}' | tr -d '%,')
chrg=$(acpi | awk '{print $3}' | tr -d '%,')
tmu=$(date | awk '{print $5}' | cut -d: -f1,2)
upt=$(uptime | awk -F, '{sub(".*up ",x,$1);print $1}')
task=$(task ids)
wat=$(echo - | awk "{printf \"%.1f\", $(($(cat /sys/class/power_supply/BAT0/current_now) * \
  $(cat /sys/class/power_supply/BAT0/voltage_now))) / 1000000000000 }")

cpu=${cpu%.*}
mem=${mem%.*}

foreground="#[fg=colour15]"
blackTX="#[fg=colour0]"
blackBG="#[bg=colour0]"
accentTX="#[fg=colour1]"
accentBG="#[bg=colour1]"
orangeBG="#[bg=colour208]"
orangeTX="#[fg=colour208]"
redBG="#[bg=colour124]"
redTX="#[fg=colour124]"
greenBG="#[bg=colour40]"
greenTX="#[fg=colour40]"
grayBG="#[bg=colour7]"
grayTX="#[fg=colour7]"
sealTX="#[fg=colour59]"
defaBG="#[bg=default]"
defaTX="#[fg=default]"
BLD="#[bold]"
NLD="#[nobold]"

[[ $bat -le 10 ]] && grayBG=$redBG grayTX=$redTX accentBG=$redBG accentTX=$redTX foreground=$blackTX

if [ $(cat /proc/acpi/bbswitch | awk 'NF>1{print $NF}') == ON ]; then
    power="$sealTX $redTX$BLD$wat W $NLD"
else
    power="$sealTX $wat W "
fi

battery="$redTX$redBG $blackTX$bat%$redBG "
[[ "$chrg" != "Discharging" ]] && battery="$accentTX$accentBG $foreground$bat% $accentBG "

memo="$greyTX$greyBG $blackTX$mem% "
spacer="$blackTX$blackBG"

if (( cpu > 80 )); then
    proc="$redTX $redBG $BLD$foreground$cpu% "
elif (( cpu > 50 )); then
    proc="$orangeTX$orangeBG $BLD$foreground$cpu% "
else
    proc="$grayTX$grayBG $blackTX$cpu% "
fi

RIGHT_STATUS="$power$proc$memo$spacer$battery"

main="$accentBG$foreground $BLD$tmu$NLD $accentTX$grayBG"
name="$blackTX $netspeed $grayTX$defaBG"


if [[ -n "${task/[ ]*\n/}" ]]
then
    utim="$sealTX #S/#W $blackTX$redBG $BLD$blackTX$task$redTX $NLD$blackBG"
else
    utim="$sealTX #S/#W "
fi


LEFT_STATUS="$main$name$utim"

if [ "$1" == "RIGHT" ] ;then
    echo $RIGHT_STATUS
elif [ "$1" == "LEFT" ] ;then
    echo $LEFT_STATUS
fi
