#!/bin/sh
#super +  {a,s,w,d}
#   focusmover {west,south,north,east}
bspc config pointer_follows_monitor true;
bspc config pointer_follows_focus true;
dir=$@;
if ! bspc node -f $dir; then
  if ! bspc desktop -f $dir; then
    bspc monitor -f $dir;
  fi;
fi;
