#!/usr/bin/env bash

clipp=$(gpick -pso --no-newline)
clipp=${clipp:1:6}

sed -i "1s/.*/*accent:    ""#$clipp/" ~/.Xdefaults
sed -i --follow-symlinks "/accent:/c\	accent: #$clipp\;" "$HOME/.config/rofi/rofi_full"
sed -i --follow-symlinks "/accent:/c\	accent: #$clipp\;" "$HOME/.config/rofi/rofi_bar"
sed -i --follow-symlinks "/accent =/c\	accent = #$clipp" "$HOME/.config/polybar/polybar"
sed -i --follow-symlinks "/keyhlcolor/c\	keyhlcolor = #$clipp\FF" "$HOME/.config/i3lock/lock"

sed -i "1s/.*/*accent:    ""#$clipp/" ~/Dots/.Xdefaults
sed -i --follow-symlinks "/define/c\#define accent		#$clipp"  ~/Dots/.Xdefaults
sed -i --follow-symlinks "/accent:/c\	accent: #$clipp\;" "$HOME/Dots/.config/rofi/rofi_full"
sed -i --follow-symlinks "/accent:/c\	accent: #$clipp\;" "$HOME/Dots/.config/rofi/rofi_bar"
sed -i --follow-symlinks "/accent =/c\	accent = #$clipp" "$HOME/Dots/.config/polybar/polybar"
sed -i --follow-symlinks "/keyhlcolor/c\	keyhlcolor = #$clipp\FF" "$HOME/Dots/.config/i3lock/lock"
sed -i --follow-symlinks "/color5 = /c\	color5 = '#$clipp'\," "$HOME/Dots/.config/conky/conky"
			

xrdb -load ~/.Xdefaults;
i3-msg reload; 
i3-msg restart;
pkill -USR1 -x sxhkd;
