#!/bin/sh

# Take password prompt from STDIN, print password to STDOUT
# the sed piece just removes the colon from the provided
# prompt: rofi -p already gives us a colon
rofi -theme /home/trim/.i3/rofii/rofi_pass -m 0 -fullscreen \
	-dmenu \
	-password \
	-padding 2000 \
	-no-fixed-num-lines \
	-p "$(printf " -         " | sed s/://)"
