#!/bin/bash

#RECDIR=/home/trim/Videos
RECDIR=/media/trim/indrive/Casts

if pgrep ffmpeg &>/dev/null; then
	pkill ffmpeg
else
	while [[ -f $RECDIR/screencast$n.mkv ]]
	do
		n=$((n+1))
	done
	filename="$RECDIR/screencast$n.mkv"

	ffmpeg -y \
	-f x11grab \
	-s $(xdpyinfo | grep dimensions | awk '{print $2;}') \
	-i :0.0 \
	-f alsa -i default \
	-c:v libx264 -r 30 -c:a flac $filename
	#-c:v ffvhuff -r 30 -c:a flac $filename
	#-f pulse -ac 1 -ar 44100 -i default \
fi
