#!/bin/bash
home=/home/trim
#dest=/media/trim/data/LINUX
dest=/home/trim/dotfiles

rsync -r -t -v --progress -s $home/.bresilla $dest

rsync -r -t -v --progress -s $home/.alias $dest
#rsync -r -t -v --progress -s $home/.antigen $dest
rsync -r -t -v --progress -s $home/.apps $dest
rsync -r -t -v --progress -s $home/.boot $dest
rsync -r -t -v --progress -s $home/.fonts $dest
rsync -r -t -v --progress -s $home/.fpath $dest
rsync -r -t -v --progress -s $home/.i3 $dest
#rsync -r -t -v --progress -s $home/.icons $dest
rsync -r -t -v --progress -s $home/.notes $dest
rsync -r -t -v --progress -s $home/.scripts $dest
#rsync -r -t -v --progress -s $home/.themes $dest
rsync -r -t -v --progress -s $home/.tmux $dest
rsync -r -t -v --progress -s $home/.wallpapers $dest
rsync -r -t -v --progress -s $home/.zsh $dest


rsync -az --progress -s $home/.bashrc $dest
rsync -az --progress -s $home/.zshrc $dest
rsync -az --progress -s $home/.spacevim $dest
#rsync -az --progress -s $home/.tmux.conf $dest
rsync -az --progress -s $home/.Xdefaults $dest

