#!/bin/bash

screen_width=$(xrandr | grep '*' | awk 'NR==1 {print substr($1,1,4)}')
screen_heigh=$(xrandr | grep '*' | awk 'NR==1 {print substr($1,6,4)}')
mouse_position=$(xdotool getmouselocation | awk '{print substr($1,3,4)}')


if [ -z "$3" ] ; then
	window_width=$(expr $screen_width / 2)
else
    window_width=$3
fi

if [ -z "$4" ] ; then
	window_heigh=$(expr $screen_heigh / 2)
else
    window_heigh=$4
fi

if [ -z "$5" ] ; then
	xoffset=$(expr $screen_width / 2 - $window_width / 2)
else
    xoffset=$5
fi

if [ -z "$6" ] ; then
	yoffset=$(expr $screen_heigh / 2 - $window_heigh / 2)
else
    yoffset=$6
fi


exec ~/.scripts/dropop -w $window_width -h $window_heigh -x $xoffset -y $yoffset -n $2 -f "-e bash -c '$1'" urxvt
