#!/bin/bash

if [ -z "$2" ] ; then
	window_width=1920
	window_heigh=780
else
    window_width=$(echo $2 | awk '{print substr($1,1,4)}')
    window_heigh=$(echo $2 | awk '{print substr($1,6,4)}')
fi

if [ -z "$3" ] ; then
	terminal=urxvt
else
    terminal=$3
fi


screen_width=$(xrandr | grep '*' | awk 'NR==1 {print substr($1,1,4)}')
screen_heigh=$(xrandr | grep '*' | awk 'NR==1 {print substr($1,6,4)}')
mouse_position=$(xdotool getmouselocation | awk '{print substr($1,3,4)}')

xoffset=$(expr $screen_width / 2 - $window_width / 2)
yoffset=$(expr $screen_heigh / 2 - $window_heigh / 2)
exec ~/.scripts/dropop -w $window_width -h $window_heigh -x $xoffset -y $yoffset -n $1 -f "-e bash -c '$1'" $terminal
