#!/bin/bash

BROWSER="firefox"
bookmarks="$HOME/Dots/.assets/.notes/bookmarks.wiki"


output=$(cat $bookmarks | awk '{print $1}' | rofi -theme /home/trim/.i3/rofi2 -width 1500 -dmenu -i -p 'bookmarks: ')
choice=$?
    
if [ $choice -ne 0 ]; then
    	echo "$choice"
else
	url=$(cat $bookmarks | grep "$output" | awk '{print $2}');
	echo $url
    if [ ${#url} -gt 0 ]; then
        $BROWSER $url
    fi
fi
