#!/bin/bash
another=$(echo "locate
websearch
youtube
bookmarks" | awk '{print $(NF-1)}' | rofi -theme /home/trim/.i3/rofi2 -width 1500 -dmenu -i -p "search: ")


if [ "$another" == "locate" ] ; then
	find /media/trim/indrive/Code | rofi -theme /home/trim/.i3/rofi2 -width 1500 -threads 0 -dmenu -i -p 'locate:' | xargs -r -0 xdg-open;

elif [ "$another" == "websearch" ] ; then
	surfraw -browser=firefox-trunk $(sr -elvi | awk -F'-' '{print $1}' | sed '/:/d' | awk '{$1=$1};1' | rofi -theme /home/trim/.i3/rofi2 -width 1500 -kb-row-select 'Tab' -kb-row-tab 'Control+space' -dmenu -i -p 'websearch: ')

elif [ "$another" == "youtube" ] ; then
	exec ~/.i3/rofii/uplay;

elif [ "$another" == "bookmarks" ] ; then
	exec ~/.i3/rofii/marks;
else
    echo $another
fi



