#!/bin/bash

ROFI_OPTIONS=(-theme $HOME/.i3/rofii/rofi_full -m 0 -fullscreen)

clipp=$(xsel --clipboard)
clipp=${clipp:1:6}

if [[ $clipp =~ ^([[:xdigit:]]{3}){1,2}$ ]]; then 
	another=$(echo "accent
background
selected" | awk '{print $(NF-1)}' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "COLOURS: ")


	if [ "$another" == "accent" ] ; then
		sed -i "1s/.*/*accent:    ""#$clipp/" ~/.Xdefaults
		sed -i --follow-symlinks "/accent:/c\	accent: #$clipp\;" "$HOME/.i3/rofii/rofi_full"
		sed -i --follow-symlinks "/accent:/c\	accent: #$clipp\;" "$HOME/.i3/rofii/rofi_bar"
		sed -i --follow-symlinks "/accent:/c\	accent: #$clipp\;" "$HOME/.i3/rofii/rofi_menu"
		sed -i --follow-symlinks "/accent =/c\	accent = #$clipp" "$HOME/.i3/polybar/polybar"
		sed -i --follow-symlinks "/keyhlcolor/c\	keyhlcolor = #$clipp\FF" "$HOME/.i3/i3lock/lock"

		sed -i --follow-symlinks "/accent:/c\	accent: #$clipp\;" "$HOME/Dots/.i3/rofii/rofi_full"
		sed -i --follow-symlinks "/accent:/c\	accent: #$clipp\;" "$HOME/Dots/.i3/rofii/rofi_bar"
		sed -i --follow-symlinks "/accent:/c\	accent: #$clipp\;" "$HOME/Dots/.i3/rofii/rofi_menu"
		sed -i --follow-symlinks "/accent =/c\	accent = #$clipp" "$HOME/Dots/.i3/polybar/polybar"
		sed -i --follow-symlinks "/keyhlcolor/c\	keyhlcolor = #$accent\FF" "$HOME/Dots/.i3/i3lock/lock"
			

	elif [ "$another" == "background" ] ; then
		sed -i --follow-symlinks "/URxvt.background:/c\	 URxvt.background: #$clipp"  ~/.Xdefaults
		sed -i --follow-symlinks "/bckgrd:/c\	bckgrd: #$clipp\;" "$HOME/.i3/rofii/rofi_bar"
		sed -i --follow-symlinks "/bckgrd:/c\	bckgrd: #$clipp\;" "$HOME/.i3/rofii/rofi_menu"
		sed -i --follow-symlinks "/bckgrd =/c\	bckgrd = #$clipp" "$HOME/.i3/polybar/polybar"

		sed -i --follow-symlinks "/bckgrd:/c\	bckgrd: #$clipp\;" "$HOME/Dots/.i3/rofii/rofi_bar"
		sed -i --follow-symlinks "/bckgrd:/c\	bckgrd: #$clipp\;" "$HOME/Dots/.i3/rofii/rofi_menu"
		sed -i --follow-symlinks "/bckgrd =/c\	bckgrd = #$clipp" "$HOME/Dots/.i3/polybar/polybar"
		

	elif [ "$another" == "selected" ] ; then
		sed -i --follow-symlinks "/select:/c\	select: #$clipp\;" "$HOME/.i3/rofii/rofi_bar"
		sed -i --follow-symlinks "/select:/c\	select: #$clipp\;" "$HOME/.i3/rofii/rofi_menu"
		sed -i --follow-symlinks "/select =/c\	select = #$clipp" "$HOME/.i3/polybar/polybar"

		sed -i --follow-symlinks "/select:/c\	select: #$clipp\;" "$HOME/Dots/.i3/rofii/rofi_bar"
		sed -i --follow-symlinks "/select:/c\	select: #$clipp\;" "$HOME/Dots/.i3/rofii/rofi_menu"
		sed -i --follow-symlinks "/select =/c\	select = #$clipp" "$HOME/Dots/.i3/polybar/polybar"

	fi
	xrdb -load ~/.Xdefaults
	i3-msg reload; 
	i3-msg restart;
else
    echo "invalid color"; 
fi
