#!/bin/bash

ROFI_OPTIONS=(-theme /home/trim/.i3/rofii/rofi_full -m 0 -fullscreen)

another=$(echo "I3
CONFS
SCRIPTS
FUNCTIS
MENU
MISC
TMUX" | awk '{print $(NF-1)}' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "SYSTEM: ")

file_it(){
	if [[ -f $1 ]]; then
	  gedit $1
	else
	  touch $1
	  chmod +x $1
	  xdg-open $1
	fi
}

list_it(){
	selected=$(ls "$2/" | rofi "${ROFI_OPTIONS[@]}" -dmenu -p "$1: ")
	[[ -z $selected ]] && exit
	file_it $2/$selected
}


if [ "$another" == "CONFS" ] ; then
	selected=$(echo "$HOME/Dots/.zshrc
$HOME/Dots/.bashrc
$HOME/Dots/.tmux.conf
$HOME/Dots/.spacevim
$HOME/Dots/.alias
$HOME/Dots/.config/ranger/rc.conf" | rofi "${ROFI_OPTIONS[@]}" -dmenu -p "shell: ")
	[[ -z $selected ]] && exit
	gedit $selected

elif [ "$another" == "I3" ] ; then
	list_it i3 /home/trim/Dots/.i3;

elif [ "$another" == "SCRIPTS" ] ; then
	list_it scripts /home/trim/Dots/.scripts;

elif [ "$another" == "FUNCTIS" ] ; then
	list_it functis /home/trim/Dots/.func;

elif [ "$another" == "MENU" ] ; then
	list_it rofi /home/trim/Dots/.i3/rofii/menu;
	
elif [ "$another" == "MISC" ] ; then
	list_it misc /home/trim/Dots/.i3/misc;
	
elif [ "$another" == "TMUX" ] ; then
	list_it misc /home/trim/Dots/.tmux;

else
    echo $another
fi



