#!/bin/bash

ROFI_OPTIONS=(-theme /home/bresilla/.i3/rofii/rofi_full -m 0 -fullscreen)

another=$(echo "I3WM
SHELL
SCRIPTS
FUNCTIS
MENUS
ZSH" | awk '{print $(NF-1)}' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "SYSTEM: ")

file_it(){
	if [[ -f $1 ]]; then
	  gedit $1
	else
	  touch $1
	  chmod +x $1
	  xdg-open $1
	fi
}

list_it(){
	selected=$(ls "$2/" | rofi "${ROFI_OPTIONS[@]}" -dmenu -p "$1: ")
	[[ -z $selected ]] && exit
	file_it $2/$selected
}


if [ "$another" == "SHELL" ] ; then
	selected=$(echo "$HOME/Dots/.zshrc
$HOME/Dots/.bashrc
$HOME/Dots/.tmux.conf
$HOME/Dots/.spacevim
$HOME/Dots/.alias
$HOME/Dots/.config/ranger/rc.conf
$HOME/.Xdefaults" | rofi "${ROFI_OPTIONS[@]}" -dmenu -p "shell: ")
	[[ -z $selected ]] && exit
	gedit $selected

elif [ "$another" == "I3WM" ] ; then
	list_it i3 /home/bresilla/Dots/.i3;

elif [ "$another" == "SCRIPTS" ] ; then
	list_it scripts /home/bresilla/Dots/.scripts;

elif [ "$another" == "FUNCTIS" ] ; then
	list_it functis /home/bresilla/Dots/.func;

elif [ "$another" == "MENUS" ] ; then
	list_it rofi /home/bresilla/Dots/.i3/rofii/menu;

elif [ "$another" == "ZSH" ] ; then
	list_it misc /home/bresilla/Dots/.zsh;

else
    echo $another
fi



