#!/bin/bash
ROFI_OPTIONS=(-theme /home/bresilla/.i3/rofii/rofi_full -m 0 -fullscreen)

another=$(echo "I3WM
SHELL
SCRIPTS
FUNCTIS
MENUS
TMUX
ZSH" | awk '{print $(NF-1)}' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "SYSTEM: ")



browse(){
	selected=$(ls "$1/" | rofi "${ROFI_OPTIONS[@]}" -dmenu -p "$1: ")
	[[ -z $selected ]] && exit
	if [[ -f $1/$selected ]]; then
		gedit $1/$selected
	elif [[ -d $1/$selected ]]; then
		browse $1/$selected
	else
		touch $1/$selected
		chmod +x $1/$selected
		gedit $1/$selected
	fi
}



if [ "$another" == "SHELL" ] ; then
	selected=$(echo "$HOME/Dots/.zshrc
$HOME/Dots/.bashrc
$HOME/Dots/.tmux.conf
$HOME/Dots/.spacevim
$HOME/Dots/.alias
$HOME/Dots/.config/ranger/rc.conf
$HOME/.Xdefaults" | rofi "${ROFI_OPTIONS[@]}" -dmenu -p "shell: ")
	[[ -z $selected ]] && exit
	gedit $selected

elif [ "$another" == "I3WM" ] ; then
	browse /home/bresilla/Dots/.i3;

elif [ "$another" == "SCRIPTS" ] ; then
	browse /home/bresilla/Dots/.scripts;

elif [ "$another" == "FUNCTIS" ] ; then
	browse /home/bresilla/Dots/.func;

elif [ "$another" == "MENUS" ] ; then
	browse /home/bresilla/Dots/.i3/rofii/menu;

elif [ "$another" == "TMUX" ] ; then
	browse /home/bresilla/Dots/.tmux;

elif [ "$another" == "ZSH" ] ; then
	browse /home/bresilla/Dots/.zsh;

else
    echo $another
fi
