#!/bin/bash

source $1

# Window title
ROFI_TEXT=$title

THEME="/home/trim/.i3/rofii/rofi_menu"
LOC=1
YOFF=58
XOFF=3138
WIDTH=18

ROFI_OPTIONS=(-theme "$THEME" -m 0 -location "$LOC" -yoffset "$YOFF" -xoffset "$XOFF" -width $WIDTH)


launcher_options=(-dmenu -i -lines "${#menu[@]}" -p "${ROFI_TEXT}" "${ROFI_OPTIONS[@]}") 
launcher=(rofi "${launcher_options[@]}")
selection="$(printf '%s\n' "${!menu[@]}" | sort | "${launcher[@]}")"

if [[ -n $selection ]]
then
    exec ${menu[${selection}]}
fi

