#!/bin/bash

ROFI_OPTIONS=(-theme $HOME/.i3/rofii/rofi_full -m 0 -fullscreen)

another=$(echo "LOCK
LOGOUT
REBOOT
POWEROFF" | awk '{print $(NF-1)}' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "SYSTEM: ")

script2bin(){
	cat /home/bresilla/pass | sudo -S cp /home/bresilla/Dots/.scripts/* /usr/local/sbin/
}

if [ "$another" == "LOCK" ] ; then
	exec ~/.i3/misc/blurlock;
		
elif [ "$another" == "LOGOUT" ] ; then
	prompt "i3-msg exit" LOGOUT
	
elif [ "$another" == "REBOOT" ] ; then
	prompt "reboot" REBOOT
	
elif [ "$another" == "POWEROFF" ] ; then
	prompt "poweroff" POWEROFF	

else
    echo $another
fi


