#!/bin/bash

ROFI_OPTIONS=(-theme /home/trim/.i3/rofii/rofi_full -m 0 -fullscreen)

another=$(echo "RELOAD
ACCENT
LOCK
LOGOUT
REBOOT
POWEROFF" | awk '{print $(NF-1)}' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "SYSTEM: ")

script2bin(){
	cat /home/trim/pass | sudo -S cp /home/trim/Dots/.scripts/* /usr/local/sbin/
}

if [ "$another" == "RELOAD" ] ; then
	xrdb -load ~/.Xdefaults; 
	i3-msg reload; 
	i3-msg restart;
	script2bin

elif [ "$another" == "ACCENT" ] ; then
	exec ~/.i3/misc/accent;
	
elif [ "$another" == "LOCK" ] ; then
	exec ~/.i3/misc/blurlock;
		
elif [ "$another" == "LOGOUT" ] ; then
	prompt "i3-msg exit" LOGOUT
	
elif [ "$another" == "REBOOT" ] ; then
	prompt "reboot" REBOOT
	
elif [ "$another" == "POWEROFF" ] ; then
	prompt "poweroff" POWEROFF
else
    echo $another
fi


